version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    networks:
      - backend


  blogservice:
    image: villsource/blogservice
    environment:
      DB_CONNECTION_STRING: Server=blog-database;Database=BlogService;User=sa;Password=P@ssword;TrustServerCertificate=True;
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - backend



  blog-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword
    ports:
      - "1434:1433"
    volumes:
      - "blog-service:/var/opt/mssql"
    networks:
      - backend







  authenticationservice:
    image: villsource/authenticationservice
    environment: 
      DB_CONNECTION_STRING: Server=blog-database;Database=authentication;User=sa;Password=P@ssword;TrustServerCertificate=True;
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - backend









volumes:
  blog-service:

networks:
  backend:
